services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - redis-data:/data

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=secret
        ports:
            - 8081:8081
        depends_on:
            - redis

    # db:
    #   image: postgres
    #   restart: always
    #   environment:
    #     POSTGRES_PASSWORD: secret
    #     POSTGRES_USER: appuser
    #   ports:
    #     - 5432:5432

    sql:
        image: mcr.microsoft.com/azure-sql-edge
        container_name: sql
        ports:
            - '1433:1433'
        environment:
            ACCEPT_EULA: '1'
            MSSQL_SA_PASSWORD: 'Passw0rd'
            MSSQL_PID: 'Developer'
            MSSQL_USER: 'SA'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    redis-data:
